# Generated by Django 2.2.7 on 2019-11-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191120_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_date',
            field=models.IntegerField(default=0),
        ),
    ]
