# Generated by Django 2.2.7 on 2019-11-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191120_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='obtained_marks',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='total_marks',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
