# Generated by Django 2.2.7 on 2019-11-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191120_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default='Intern', max_length=100),
            preserve_default=False,
        ),
    ]
